"""Add counselor system tables

Revision ID: 57da5844e42e
Revises: fde9daab2aa6
Create Date: 2025-06-30 11:35:58.460190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57da5844e42e'
down_revision: Union[str, None] = 'fde9daab2aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counselors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('specialties', sa.JSON(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('offline', 'online', 'busy', 'away', name='counselorstatus'), nullable=True),
    sa.Column('max_concurrent_sessions', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counselors_email'), 'counselors', ['email'], unique=True)
    op.create_index(op.f('ix_counselors_id'), 'counselors', ['id'], unique=False)
    op.create_table('consultation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('counselor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['counselor_id'], ['counselors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_requests_id'), 'consultation_requests', ['id'], unique=False)
    op.add_column('consultations', sa.Column('counselor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'consultations', 'counselors', ['counselor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_column('consultations', 'counselor_id')
    op.drop_index(op.f('ix_consultation_requests_id'), table_name='consultation_requests')
    op.drop_table('consultation_requests')
    op.drop_index(op.f('ix_counselors_id'), table_name='counselors')
    op.drop_index(op.f('ix_counselors_email'), table_name='counselors')
    op.drop_table('counselors')
    # ### end Alembic commands ###
