"""add_voice_call_fields_to_consultation

Revision ID: c4ebbb1dc3d0
Revises: c6314394cb3f
Create Date: 2025-07-25 16:45:30.593010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ebbb1dc3d0'
down_revision: Union[str, None] = 'c6314394cb3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('voice_call_active', sa.Boolean(), nullable=True))
    op.add_column('consultations', sa.Column('voice_call_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('consultations', sa.Column('voice_call_ended_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'voice_call_ended_at')
    op.drop_column('consultations', 'voice_call_started_at')
    op.drop_column('consultations', 'voice_call_active')
    # ### end Alembic commands ###
