"""add_voice_message_support

Revision ID: c6314394cb3f
Revises: e9bd0ff9b049
Create Date: 2025-07-25 16:40:18.325790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6314394cb3f'
down_revision: Union[str, None] = 'e9bd0ff9b049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultation_messages', sa.Column('voice_file_path', sa.String(length=500), nullable=True))
    op.add_column('consultation_messages', sa.Column('voice_duration', sa.Integer(), nullable=True))
    op.add_column('consultation_messages', sa.Column('voice_file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation_messages', 'voice_file_size')
    op.drop_column('consultation_messages', 'voice_duration')
    op.drop_column('consultation_messages', 'voice_file_path')
    # ### end Alembic commands ###
