"""add admin tables and refresh tokens

Revision ID: e9bd0ff9b049
Revises: 34a589d805b1
Create Date: 2025-07-23 10:59:12.926166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9bd0ff9b049'
down_revision: Union[str, None] = '34a589d805b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'admin', 'moderator', name='adminrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('admin_refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_refresh_tokens_id'), 'admin_refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_admin_refresh_tokens_token_hash'), 'admin_refresh_tokens', ['token_hash'], unique=True)
    op.create_foreign_key(None, 'consultation_requests', 'counselors', ['counselor_id'], ['id'])
    op.create_foreign_key(None, 'consultations', 'counselors', ['counselor_id'], ['id'])
    op.alter_column('counseling_fields', 'code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('counseling_fields', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index('idx_counseling_fields_active', table_name='counseling_fields')
    op.drop_index('idx_counseling_fields_code', table_name='counseling_fields')
    op.drop_index('idx_counseling_fields_order', table_name='counseling_fields')
    op.create_index(op.f('ix_counseling_fields_id'), 'counseling_fields', ['id'], unique=False)
    op.drop_column('counseling_fields', 'updated_at')
    op.alter_column('counselors', 'counseling_fields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='상담 분야 ID 목록 (JSON 배열)',
               existing_nullable=False)
    op.alter_column('counselors', 'is_approved',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='관리자 승인 여부',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('counselors', 'max_concurrent_sessions',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='동시 상담 가능 수',
               existing_nullable=True,
               existing_server_default=sa.text('3'))
    op.drop_constraint('counselors_email_key', 'counselors', type_='unique')
    op.drop_constraint('counselors_phone_key', 'counselors', type_='unique')
    op.drop_constraint('counselors_username_key', 'counselors', type_='unique')
    op.drop_index('idx_counselors_active', table_name='counselors')
    op.drop_index('idx_counselors_approved', table_name='counselors')
    op.drop_index('idx_counselors_email', table_name='counselors')
    op.drop_index('idx_counselors_phone', table_name='counselors')
    op.drop_index('idx_counselors_status', table_name='counselors')
    op.drop_index('idx_counselors_username', table_name='counselors')
    op.create_index(op.f('ix_counselors_email'), 'counselors', ['email'], unique=True)
    op.create_index(op.f('ix_counselors_id'), 'counselors', ['id'], unique=False)
    op.create_index(op.f('ix_counselors_phone'), 'counselors', ['phone'], unique=True)
    op.create_index(op.f('ix_counselors_username'), 'counselors', ['username'], unique=True)
    op.drop_table_comment(
        'counselors',
        existing_comment='상담사 정보 테이블 (필수 필드만)',
        schema=None
    )
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Refresh Token의 해시값 (보안을 위해 원본 토큰 대신 해시 저장)',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               comment=None,
               existing_comment='토큰 발급 시 사용자 브라우저 정보',
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               comment=None,
               existing_comment='토큰 발급 시 클라이언트 IP 주소',
               existing_nullable=True)
    op.drop_index('idx_refresh_tokens_active', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_counselor_id', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_foreign_key(None, 'refresh_tokens', 'counselors', ['counselor_id'], ['id'])
    op.drop_table_comment(
        'refresh_tokens',
        existing_comment='상담사 Refresh Token 관리 테이블',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'refresh_tokens',
        '상담사 Refresh Token 관리 테이블',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.create_unique_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', ['token_hash'])
    op.create_index('idx_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('idx_refresh_tokens_counselor_id', 'refresh_tokens', ['counselor_id'], unique=False)
    op.create_index('idx_refresh_tokens_active', 'refresh_tokens', ['is_active'], unique=False)
    op.alter_column('refresh_tokens', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               comment='토큰 발급 시 클라이언트 IP 주소',
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'user_agent',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               comment='토큰 발급 시 사용자 브라우저 정보',
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Refresh Token의 해시값 (보안을 위해 원본 토큰 대신 해시 저장)',
               existing_nullable=False)
    op.create_table_comment(
        'counselors',
        '상담사 정보 테이블 (필수 필드만)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_counselors_username'), table_name='counselors')
    op.drop_index(op.f('ix_counselors_phone'), table_name='counselors')
    op.drop_index(op.f('ix_counselors_id'), table_name='counselors')
    op.drop_index(op.f('ix_counselors_email'), table_name='counselors')
    op.create_index('idx_counselors_username', 'counselors', ['username'], unique=False)
    op.create_index('idx_counselors_status', 'counselors', ['status'], unique=False)
    op.create_index('idx_counselors_phone', 'counselors', ['phone'], unique=False)
    op.create_index('idx_counselors_email', 'counselors', ['email'], unique=False)
    op.create_index('idx_counselors_approved', 'counselors', ['is_approved'], unique=False)
    op.create_index('idx_counselors_active', 'counselors', ['is_active'], unique=False)
    op.create_unique_constraint('counselors_username_key', 'counselors', ['username'])
    op.create_unique_constraint('counselors_phone_key', 'counselors', ['phone'])
    op.create_unique_constraint('counselors_email_key', 'counselors', ['email'])
    op.alter_column('counselors', 'max_concurrent_sessions',
               existing_type=sa.INTEGER(),
               comment='동시 상담 가능 수',
               existing_nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('counselors', 'is_approved',
               existing_type=sa.BOOLEAN(),
               comment='관리자 승인 여부',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('counselors', 'counseling_fields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='상담 분야 ID 목록 (JSON 배열)',
               existing_nullable=False)
    op.add_column('counseling_fields', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_counseling_fields_id'), table_name='counseling_fields')
    op.create_index('idx_counseling_fields_order', 'counseling_fields', ['display_order'], unique=False)
    op.create_index('idx_counseling_fields_code', 'counseling_fields', ['code'], unique=False)
    op.create_index('idx_counseling_fields_active', 'counseling_fields', ['is_active'], unique=False)
    op.alter_column('counseling_fields', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('counseling_fields', 'code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_constraint(None, 'consultation_requests', type_='foreignkey')
    op.drop_index(op.f('ix_admin_refresh_tokens_token_hash'), table_name='admin_refresh_tokens')
    op.drop_index(op.f('ix_admin_refresh_tokens_id'), table_name='admin_refresh_tokens')
    op.drop_table('admin_refresh_tokens')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
