"""Add consultation tables

Revision ID: fde9daab2aa6
Revises: 
Create Date: 2025-06-30 08:26:34.050915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fde9daab2aa6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_code', sa.String(length=9), nullable=False),
    sa.Column('user_nickname', sa.String(length=100), nullable=False),
    sa.Column('character_type_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'active', 'completed', 'terminated', name='consultationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_card_issued', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['character_type_id'], ['final_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_consultation_code'), 'consultations', ['consultation_code'], unique=True)
    op.create_index(op.f('ix_consultations_id'), 'consultations', ['id'], unique=False)
    op.create_table('consultation_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('card_data', sa.JSON(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consultation_id')
    )
    op.create_index(op.f('ix_consultation_cards_id'), 'consultation_cards', ['id'], unique=False)
    op.create_table('consultation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.Enum('user', 'character', name='sendertype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('message_type', sa.Enum('text', 'system', 'image', name='messagetype'), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_messages_id'), 'consultation_messages', ['id'], unique=False)
    op.alter_column('calculation_weights', 'weight',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('categories', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.drop_column('categories', 'created_at')
    op.alter_column('final_types', 'animal',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('final_types', 'group_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('final_types', 'one_liner',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('final_types', 'overview',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('final_types', 'greeting',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('final_types', 'hashtags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('final_types', 'strengths',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('final_types', 'weaknesses',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('final_types', 'relationship_style',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('final_types', 'behavior_pattern',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('final_types', 'strength_icons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('final_types', 'weakness_icons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint('final_types_display_order_key', 'final_types', type_='unique')
    op.drop_constraint('final_types_name_key', 'final_types', type_='unique')
    op.create_index(op.f('ix_final_types_id'), 'final_types', ['id'], unique=False)
    op.drop_column('final_types', 'display_order')
    op.drop_column('final_types', 'created_at')
    op.alter_column('intermediate_types', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('intermediate_types_display_order_key', 'intermediate_types', type_='unique')
    op.drop_constraint('intermediate_types_name_key', 'intermediate_types', type_='unique')
    op.create_index(op.f('ix_intermediate_types_id'), 'intermediate_types', ['id'], unique=False)
    op.drop_column('intermediate_types', 'created_at')
    op.alter_column('main_keywords', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('unique_main_keyword_order', 'main_keywords', type_='unique')
    op.drop_constraint('unique_main_keyword_per_category', 'main_keywords', type_='unique')
    op.create_index(op.f('ix_main_keywords_id'), 'main_keywords', ['id'], unique=False)
    op.drop_constraint('main_keywords_category_id_fkey', 'main_keywords', type_='foreignkey')
    op.create_foreign_key(None, 'main_keywords', 'categories', ['category_id'], ['id'])
    op.drop_column('main_keywords', 'created_at')
    op.alter_column('sub_keywords', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('unique_sub_keyword_order', 'sub_keywords', type_='unique')
    op.drop_constraint('unique_sub_keyword_per_main', 'sub_keywords', type_='unique')
    op.create_index(op.f('ix_sub_keywords_id'), 'sub_keywords', ['id'], unique=False)
    op.drop_constraint('sub_keywords_main_keyword_id_fkey', 'sub_keywords', type_='foreignkey')
    op.create_foreign_key(None, 'sub_keywords', 'main_keywords', ['main_keyword_id'], ['id'])
    op.drop_column('sub_keywords', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_keywords', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sub_keywords', type_='foreignkey')
    op.create_foreign_key('sub_keywords_main_keyword_id_fkey', 'sub_keywords', 'main_keywords', ['main_keyword_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sub_keywords_id'), table_name='sub_keywords')
    op.create_unique_constraint('unique_sub_keyword_per_main', 'sub_keywords', ['main_keyword_id', 'name'])
    op.create_unique_constraint('unique_sub_keyword_order', 'sub_keywords', ['main_keyword_id', 'display_order'])
    op.alter_column('sub_keywords', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('main_keywords', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'main_keywords', type_='foreignkey')
    op.create_foreign_key('main_keywords_category_id_fkey', 'main_keywords', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_main_keywords_id'), table_name='main_keywords')
    op.create_unique_constraint('unique_main_keyword_per_category', 'main_keywords', ['category_id', 'name'])
    op.create_unique_constraint('unique_main_keyword_order', 'main_keywords', ['category_id', 'display_order'])
    op.alter_column('main_keywords', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('intermediate_types', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_intermediate_types_id'), table_name='intermediate_types')
    op.create_unique_constraint('intermediate_types_name_key', 'intermediate_types', ['name'])
    op.create_unique_constraint('intermediate_types_display_order_key', 'intermediate_types', ['display_order'])
    op.alter_column('intermediate_types', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('final_types', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('final_types', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_final_types_id'), table_name='final_types')
    op.create_unique_constraint('final_types_name_key', 'final_types', ['name'])
    op.create_unique_constraint('final_types_display_order_key', 'final_types', ['display_order'])
    op.alter_column('final_types', 'weakness_icons',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('final_types', 'strength_icons',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('final_types', 'behavior_pattern',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('final_types', 'relationship_style',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('final_types', 'weaknesses',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('final_types', 'strengths',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('final_types', 'hashtags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('final_types', 'greeting',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('final_types', 'overview',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('final_types', 'one_liner',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('final_types', 'group_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('final_types', 'animal',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('categories', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    op.alter_column('categories', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('calculation_weights', 'weight',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_consultation_messages_id'), table_name='consultation_messages')
    op.drop_table('consultation_messages')
    op.drop_index(op.f('ix_consultation_cards_id'), table_name='consultation_cards')
    op.drop_table('consultation_cards')
    op.drop_index(op.f('ix_consultations_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_consultation_code'), table_name='consultations')
    op.drop_table('consultations')
    # ### end Alembic commands ###
