name: Discord Notification

on:
  push:  
    branches:
      - main  

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Discord notification
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "✅ 새로운 커밋이 올라왔습니다! \n- 메시지: ${{ github.event.head_commit.message }} \n- 작성자: ${{ github.event.head_commit.author.name }}"}' \
               ${{ secrets.DISCORD_WEBHOOK }}